spring:
    application:
        name: reviews
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/java-jpa-specifications?autoReconnect=true&useSSL=false&charset=utf8mb4_unicode_ci&serverTimezone=UTC
        username: java-jpa-specifications
        password: java-jpa-specifications
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
        show-sql: false
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            jdbc:
              time_zone: America/Havana

server:
    port: 5002


